#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Apr 23 22:51:00 2017

@author: christopher
"""

from scipy import *
from rocketEqs import * 
import sys

g = 9.8
#[Stage 1 , Stage 2]
f_inert = [.09,.11]
isp = [350, 400]
dV = [5000,5000]
m_pay = 1000

def rocket_mass(g,f_inert, dv, isp):  
    
    stage2 = initial_mass(m_pay,f_inert[1], dV[1], g, isp[1])
    print("Stage 2 Mass;", stage2)
    
    rocketMass = initial_mass(stage2,f_inert[0], dV[0], g, isp[0])
    print("Total Rocket Mass:", rocketMass)
    
    return(rocketMass)
    
rocket_mass(g,f_inert, dv, isp)
